### ISSUE TITLE
Model training job error

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-legacy#1573]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1720016316388709

A user got an error on an RFM model training job in this project and doesn't know why -
https://arbimon.org/project/smiil-placement-monitoring/jobs 

![Image](https://github.com/rfcx/arbimon-legacy/assets/87486094/e741729e-5285-4022-a25d-ef996e86815d)

**Comment by RatreeOchn** [comment]
```
Error: cannot analize recordings in parallel Traceback (most recent call last):
  File "/var/lib/arbimon2/jobs/scripts/PatternMatching/train.py", line 382, in <module>
    results = Parallel(n_jobs=num_cores)(delayed(recnilize)(line,workingFolder,currDir,jobId,(patternSurfaces[line[4]]),log,ssim,searchMatch) for line in validationData)
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/joblib/parallel.py", line 768, in __call__
    self.retrieve()
  File "/var/lib/arbimon2/jobs/.env/local/lib/python2.7/site-packages/joblib/parallel.py", line 719, in retrieve
    raise exception
JoblibMemoryError: JoblibMemoryError
```
